### ISSUE TITLE
The data generation is so slow :(

### ISSUE THREAD

**Issue by windboy6** [TongZhangTHU/sgr#1]
Hi,

Thanks for sharing such a great job!

The data generation is so slow, have you considered uploading it to Google Cloud Drive and providing a download link?

**Comment by TongZhangTHU** [comment]
Thank you for your recognition of our work. 

Due to the large size of the data, my Google Cloud Drive currently doesn't have enough space, so I will need some time before I can upload the data. In fact, based on my experience, generating the data might be as fast as downloading it. You just need to use GPU headless rendering and run multiple tasks in parallel, which allows for very quick data generation.

**Comment by windboy6** [comment]
Ok. Thank you!
