### ISSUE TITLE
Real world data training 

### ISSUE THREAD

**Issue by haksorus** [TongZhangTHU/sgr#2]
Hello!
Thanks for amazing work

Any plans to add real world data training + evaluation?

**Comment by TongZhangTHU** [comment]
Hello! 
The training code for simulation and real-world robots is shared. To switch to real-world training, you just need to set `real_robot.apply` to `True` in the [config.yaml](https://github.com/TongZhangTHU/sgr/blob/main/conf/config.yaml#L38)  file. As for evaluation on real-world data, it's something I might consider organizing in the future, but due to my current workload, there are no immediate plans for it.
